import { CoworkingSpaceItem, CoworkingBooking, CoworkingMembershipPlan } from "@/types/coworking";

export const INITIAL_SPACES: CoworkingSpaceItem[] = [
  {
    id: "sp-hd-01",
    name: "Hot Desk 01 (Window View)",
    type: "HOT_DESK",
    area: "Ground Floor Main",
    capacity: 1,
    hourlyRate: 15000,
    dailyRate: 75000,
    monthlyRate: 1200000,
    status: "OCCUPIED",
    amenities: ["Power Socket", "High Speed WiFi 100Mbps", "Free Flow Senja Coffee"],
    currentSession: {
      guestName: "Arif Hidayat",
      company: "Freelance Designer",
      checkInTime: "09:00",
      endTime: "17:00",
      bookingCode: "CWK-20260916-01",
    },
  },
  {
    id: "sp-hd-02",
    name: "Hot Desk 02 (Focus Zone)",
    type: "HOT_DESK",
    area: "Ground Floor Main",
    capacity: 1,
    hourlyRate: 15000,
    dailyRate: 75000,
    monthlyRate: 1200000,
    status: "OCCUPIED",
    amenities: ["Power Socket", "High Speed WiFi 100Mbps", "Free Flow Senja Coffee"],
    currentSession: {
      guestName: "Siti Rahayu",
      company: "Remote Frontend Dev",
      checkInTime: "10:15",
      endTime: "18:15",
      bookingCode: "CWK-20260916-02",
    },
  },
  {
    id: "sp-hd-03",
    name: "Hot Desk 03 (Standing Desk)",
    type: "HOT_DESK",
    area: "Ground Floor Main",
    capacity: 1,
    hourlyRate: 15000,
    dailyRate: 75000,
    monthlyRate: 1200000,
    status: "AVAILABLE",
    amenities: ["Standing Desk Motorized", "Ergonomic Mat", "Dual Power Hub"],
  },
  {
    id: "sp-hd-04",
    name: "Hot Desk 04 (Quiet Corner)",
    type: "HOT_DESK",
    area: "Ground Floor Main",
    capacity: 1,
    hourlyRate: 15000,
    dailyRate: 75000,
    monthlyRate: 1200000,
    status: "AVAILABLE",
    amenities: ["Power Socket", "High Speed WiFi 100Mbps", "Desk Lamp LED"],
  },
  {
    id: "sp-dd-01",
    name: "Dedicated Desk A-01",
    type: "DEDICATED_DESK",
    area: "Mezzanine Quiet Zone",
    capacity: 1,
    hourlyRate: 25000,
    dailyRate: 120000,
    monthlyRate: 1500000,
    status: "OCCUPIED",
    amenities: ["27-inch 4K Monitor", "Locker Personal", "Ergonomic Herman Miller Chair", "24/7 Access Keycard"],
    currentSession: {
      guestName: "Budi Santoso",
      company: "Fintech Startup",
      checkInTime: "08:30",
      endTime: "20:00",
      bookingCode: "CWK-RES-089",
    },
  },
  {
    id: "sp-dd-02",
    name: "Dedicated Desk A-02",
    type: "DEDICATED_DESK",
    area: "Mezzanine Quiet Zone",
    capacity: 1,
    hourlyRate: 25000,
    dailyRate: 120000,
    monthlyRate: 1500000,
    status: "AVAILABLE",
    amenities: ["27-inch 4K Monitor", "Locker Personal", "Ergonomic Chair", "24/7 Access Keycard"],
  },
  {
    id: "sp-mr-01",
    name: "Meeting Room Seminyak (6 Pax)",
    type: "MEETING_ROOM",
    area: "VIP Meeting Wing",
    capacity: 6,
    hourlyRate: 150000,
    dailyRate: 900000,
    status: "RESERVED",
    amenities: ["65-inch 4K Smart TV", "Conference Camera 4K", "Glass Whiteboard", "Free Coffee & Tea Service"],
    currentSession: {
      guestName: "Denny Gunawan",
      company: "Agensi Digital Kreatif",
      checkInTime: "13:00",
      endTime: "15:00",
      bookingCode: "CWK-MR-20260916-01",
    },
  },
  {
    id: "sp-mr-02",
    name: "Boardroom Ubud (12 Pax)",
    type: "MEETING_ROOM",
    area: "VIP Meeting Wing",
    capacity: 12,
    hourlyRate: 275000,
    dailyRate: 1600000,
    status: "AVAILABLE",
    amenities: ["85-inch Interactive Display", "Jabra Mic Array", "Acoustic Wall Panels", "Full Catering Service"],
  },
];

export const INITIAL_BOOKINGS: CoworkingBooking[] = [
  {
    id: "bk-1",
    bookingCode: "CWK-20260916-01",
    guestName: "Arif Hidayat",
    guestPhone: "+62 812-9988-7711",
    guestEmail: "arif.uiux@gmail.com",
    company: "Freelance Designer",
    spaceId: "sp-hd-01",
    spaceName: "Hot Desk 01 (Window View)",
    spaceType: "HOT_DESK",
    bookingType: "DAILY",
    date: "16 Sep 2026",
    startTime: "09:00",
    duration: 1,
    totalAmount: 75000,
    paymentStatus: "PAID",
    checkInStatus: "CHECKED_IN",
    fnbVoucherApplied: "VOUCHER-CWK-NOMAD-10",
    notes: "Sudah bayar via QRIS Dinamis.",
  },
  {
    id: "bk-2",
    bookingCode: "CWK-20260916-02",
    guestName: "Siti Rahayu",
    guestPhone: "+62 813-4455-6677",
    guestEmail: "siti.rahayu@gmail.com",
    company: "Remote Frontend Dev",
    spaceId: "sp-hd-02",
    spaceName: "Hot Desk 02 (Focus Zone)",
    spaceType: "HOT_DESK",
    bookingType: "DAILY",
    date: "16 Sep 2026",
    startTime: "10:15",
    duration: 1,
    totalAmount: 75000,
    paymentStatus: "PAID",
    checkInStatus: "CHECKED_IN",
    fnbVoucherApplied: "VOUCHER-CWK-NOMAD-10",
  },
  {
    id: "bk-3",
    bookingCode: "CWK-MR-20260916-01",
    guestName: "Denny Gunawan",
    guestPhone: "+62 811-2233-4455",
    guestEmail: "denny@creativestudio.id",
    company: "Agensi Digital Kreatif",
    spaceId: "sp-mr-01",
    spaceName: "Meeting Room Seminyak (6 Pax)",
    spaceType: "MEETING_ROOM",
    bookingType: "HOURLY",
    date: "16 Sep 2026",
    startTime: "13:00",
    duration: 2,
    totalAmount: 300000,
    paymentStatus: "PAID",
    checkInStatus: "RESERVED",
    notes: "Minta disiapkan 6 cangkir Kopi Senja Aren sebelum meeting dimulai.",
  },
  {
    id: "bk-4",
    bookingCode: "CWK-MR-20260916-02",
    guestName: "Maya Putri",
    guestPhone: "+62 818-8877-6655",
    guestEmail: "maya@venturehub.co",
    company: "Venture Builder Hub",
    spaceId: "sp-mr-02",
    spaceName: "Boardroom Ubud (12 Pax)",
    spaceType: "MEETING_ROOM",
    bookingType: "HOURLY",
    date: "16 Sep 2026",
    startTime: "15:30",
    duration: 3,
    totalAmount: 825000,
    paymentStatus: "PENDING",
    checkInStatus: "RESERVED",
    notes: "Pitching sesi investor startup batch September.",
  },
];

export const MEMBERSHIP_PLANS: CoworkingMembershipPlan[] = [
  {
    id: "plan-nomad",
    name: "Daily Nomad Pass",
    priceFormatted: "Rp 75.000",
    priceNumber: 75000,
    billingCycle: "Harian",
    color: "border-blue-500 bg-blue-50/20",
    deskAccess: "Akses 1 Hari Hot Desk (08:00 - 22:00)",
    meetingCredits: "Diskon 10% sewa Meeting Room",
    fnbPerk: "Voucher Diskon 10% F&B Kopi Senja & Free Flow Black Coffee",
    fnbVoucherCode: "VOUCHER-CWK-NOMAD-10",
    amenities: ["WiFi 100Mbps Ultra-Fast", "Power Hub di setiap meja", "Area Pantry & Water Dispenser"],
  },
  {
    id: "plan-flexi",
    name: "Monthly Flexi 10 Pass",
    priceFormatted: "Rp 600.000",
    priceNumber: 600000,
    billingCycle: "Paket 10 Hari",
    popular: true,
    color: "border-brand-orange bg-brand-orange/5",
    deskAccess: "10x Akses Hot Desk bebas pakai dalam 30 hari",
    meetingCredits: "Gratis 2 Jam Kuota Meeting Room Seminyak",
    fnbPerk: "Voucher Diskon 15% Seluruh Menu F&B Kopi Senja",
    fnbVoucherCode: "VOUCHER-CWK-FLEXI-15",
    amenities: ["Bebas pilih area Ground / Mezzanine", "Gratis Print 20 lembar", "Komunitas Discord Dago Hub"],
  },
  {
    id: "plan-resident",
    name: "Resident Dedicated Desk",
    priceFormatted: "Rp 1.500.000",
    priceNumber: 1500000,
    billingCycle: "Bulanan",
    color: "border-purple-500 bg-purple-50/20",
    deskAccess: "Meja Khusus Tetap (Dedicated Desk) Akses 24/7",
    meetingCredits: "Gratis 6 Jam Kuota Meeting Room Seminyak / Ubud",
    fnbPerk: "Voucher Diskon 20% F&B + 1 Free Signature Coffee setiap hari",
    fnbVoucherCode: "VOUCHER-CWK-RESIDENT-20",
    amenities: [
      "Monitor 27-inch 4K & Locker Pribadi",
      "Alamat Bisnis Resmi Dago Creative Hub",
      "Layanan Penerimaan Surat / Paket",
      "Prioritas Event Dago Workshop",
    ],
  },
];
